### PR TITLE
menumanager: more menu fixes

### PR DESCRIPTION
**Pull request by se7enAte9**
Not sure what the current plan with menumanager is, feel free to close the pr if there is something else planned or if it's changing too much. 

This changes menu manager a decent amount as to how it works. There are noticeable performance improvements from these changes (from 20-30 fps in world 2 GE with 400 menu options to a consistent 40 fps.) The priority entry system has been changed to show the unprioritized entries under the prioritized ones, rather than clearing the menu and only showing the priority entries. This allows for plugins like tiles markers to still function while a plugin like shift to walk is enabled. This also fixes custom swaps with low id's not working.

Note: If there are multiple swaps in the same menu only the first one found will be applied, it'd take 10 seconds to edit it back to allowing all swaps to be applied, but I'm guessing that change was made for performance issues as it was done a couple PR's ago. It doesn't seem like swapping at this point. At least how it's currently being implemented with only swapping an option to the first entry, the swaps are basically priority entries. If everything was switched over to using priority entries instead of swaps, you'd likely see more performance improvements. 

There was one block of code that I removed and I don't think it's needed, but I'd like some verification first. See lines [197-216](https://github.com/runelite-extended/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/menus/MenuManager.java#L197).

Note: This does not fix bugs in the menuentryswapper plugin, see #805, most of those are an entirely different issue. I did test this and couldn't find anything broken, but would appreciate if someone else could test it as well if this is to be merged.

### CODE REVIEW

**Comment by sdburns1998** [comment]
Really nice work!

**Comment by se7enAte9** [comment]
I switched back to using MenuEntryAdded, this should hopefully fix #819. Reworked so that so only the left click entry is calculated rather than calculating every single swap every MenuEntryAdded event. The rest of the swaps/priority entries are calculated when the menu is opened. This is letting me get 40-50 fps with 400 menu option in world 2 ge. Will still need a lot of testing.

**Comment by se7enAte9** [comment]
If I use MenuEntryAdded, you start to run into performance issues when checking for multiple swaps to see if any single one is the first entry. As a workaround, the menus are now being checked in before render as well as using multiple threads to hopefully speed things up. My knowledge in using multiple threads is not that good, so if anyone could look over it and let me know if I'm doing something wrong or should try doing something different that'd be 👌 

Although I can't duplicate #819 when using beforerender, if it ends up still not being fixed and menuentryadded has to be used, a solution I found was to only check priority entries and hidden entries. Swaps would then be used only in right click menus, while priority/left click entries would work as expected.

Need someone to verify if they get similar performance improvements. With about 150 custom swaps, I'm sitting at 35 fps when hovering over 400 menu options, of which 10 or so look like they're being caused by non menumanager swaps in menuentryswapper

**Comment by zeruth** [comment]
Going to merge this so we can get some testers on it. Not pushing a live update quite yet. Thanks!

**Pull request merged**
