### PR TITLE
xtea: remove extra parts of xtea

### PR DESCRIPTION
**Pull request by Hermetism**
Remove XTEA Plugin
Remove XTEA HTTP-API
Remove XTEA HTTP-SERVICE

These aren't required for the cache and only served to track players.

This will not break XTEA encryption and decryption.

### CODE REVIEW

**Comment by Hermetism** [comment]
Wtf wrong repo who dis.

**Comment by ThatGamerBlue** [comment]
you gonna pr this upstream or are you just paranoid?

**Comment by Hermetism** [comment]
Why would you want to leave it in there?

Sorry it failed tests because i forget to edit a test.

**Comment by Hermetism** [comment]
So you're going to close it without even looking at it?

Yeah that isn't suspect.

**Comment by Owain94** [comment]
What's the problem with collecting xtea keys?

**Comment by Hermetism** [comment]
Why do you need them at all.

**Comment by Hermetism** [comment]
It doesn't just collect the key, It gives the players the current region to whoever runs the API.

You can track players with the XTEA Plugin and you apparently know it.

**Comment by Hermetism** [comment]
I'm not paranoid i can fucking read

**Comment by ThatGamerBlue** [comment]
Show me where it reports what player it is and I'll merge it, until then you can PR this upstream because they collect it too.

**Comment by Hermetism** [comment]
I could honestly care less about helping now tbh.

**Comment by Owain94** [comment]
They are being used for private servers, also it has nothing to do with tracking players (only xtea keys are being sent to the API you can clearly see that in the source code).

I have no idea why it's such a big deal that we collect keys to decode regions, I also don't understand why you're being angry because we don't want to merge your PR.

**Comment by Hermetism** [comment]
`I have no idea why it's such a big deal that we collect keys to decode regions, I also don't understand why you're being angry because we don't want to merge your PR.`

You don't need to collect the keys to decode the regions, I didn't break decoding regions.
I didn't come here for the run around.

**Comment by Owain94** [comment]
Read my comment again...

We collect the xtea keys, and those xtea keys are being used for private servers.
Collecting xtea keys doesn't have anything to do with tracking players we don't even have enough data sent to the API to do that.

All the xtea keys are public in our API so feel free to link them to individual players because that's simply not possible with the data we save (and again you could've seen that in the source code).

**Comment by Hermetism** [comment]
`We collect the xtea keys, and those xtea keys are being used for private servers.`

can you elaborate on that? why do you need to send the keys to your api, they can be read on the client

My changes don't break anything to do with private servers?

**Comment by Lucwousin** [comment]
You do actually need them for decoding regions. They dont exist without a reason.

Jagex sends them to you when you enter a new region and have to decode it.

Feel free to play on a branch with xtea removed, we just won't remove it from the client

**Comment by Hermetism** [comment]
`You do actually need them for decoding regions. They dont exist without a reason.`

I didn't remove that, decoding regions works fine.

**Comment by Hermetism** [comment]
You don't need it for "private servers" unless i am missing an entire aspect of this.

**Comment by Lucwousin** [comment]
Because jagex sends them to you. Private servers however dont have jagex sending them the keys, and are pretty much stuck scraping them.

Without xtea keys you can load the tiles, but not the objects on them (i think)

**Comment by Hermetism** [comment]
Ah okay that makes a lot of sense now tbh, it seems like it should be more of an opt-in kind of thing because it could be abused (not saying it is)

**Comment by chrisjohnson** [comment]
How could it be abused?

**Comment by zeruth** [comment]
Opt in would mean that nobody would opt in. Even with every player tracking it took days to get even majority coverage. Opt out is the only viable solution and that was implemented when xtea was. There is an xtea plugin you can disable. Do your research please.

**Comment by Hermetism** [comment]
> Because jagex sends them to you. Private servers however dont have jagex sending them the keys, and are pretty much stuck scraping them.
> 
> Without xtea keys you can load the tiles, but not the objects on them (i think)

https://github.com/Tomm0017/rsmod/blob/master/util/src/main/kotlin/gg/rsmod/util/io/Xtea.kt

okay i see now.

@zeruth yeah, sorry.

**Pull request closed without merging**
