### PR TITLE
Tables

### PR DESCRIPTION
**Pull request by sdburns1998**

### CODE REVIEW

**Comment by james-munson** [comment]
`Running net.runelite.client.ui.FontManagerTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 sec - in net.runelite.client.ui.FontManagerTest
Running net.runelite.client.config.ConfigManagerTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.013 sec - in net.runelite.client.config.ConfigManagerTest
Results :
Failed tests: 
  TableComponentTest.testColors:82 
Argument(s) are different! Wanted:
graphics.setColor(
    java.awt.Color[r=255,g=255,b=0]
);
-> at net.runelite.client.ui.overlay.components.table.TableComponentTest.testColors(TableComponentTest.java:82)
Actual invocation has different arguments:
graphics.setColor(
    java.awt.Color[r=0,g=0,b=0]
);
-> at net.runelite.client.ui.overlay.components.TextComponent.render(TextComponent.java:81)
Tests run: 162, Failures: 1, Errors: 0, Skipped: 4`

**Comment by james-munson** [comment]
This modifies a lot of default runelite plugins, i like how it's cleaner to use but it modifes so much. What does everyone else think?

**Comment by sdburns1998** [comment]
@james-munson forgot to added the test that was added by these commits...

Also I don't a problem with modifying existing overlays, it could result in small merge conflicts but since logic in handled in the plugin and not in the overlay they would be really small and super easy to fix.

**Comment by tomcylke** [comment]
Does this change anything visually? Too lazy to look through the code right now, but if it does would you be willing to upload a few screenshots? Thanks.

**Comment by james-munson** [comment]
> Does this change anything visually? Too lazy to look through the code right now, but if it does would you be willing to upload a few screenshots? Thanks.

No its code optimization

**Pull request merged**
