### PR TITLE
Added Camera and Hotkeys Plugin

### PR DESCRIPTION
**Pull request by james-munson**
Added Camera and Hotkeys Plugin
Combines #302  into one plugin and adds F1 remapping as well

### CODE REVIEW

**Comment by Kyleeld** [comment]
you want to keep wasd camera as its a standard RL plugin. it would be worth remaking this for a hotkey listener and merging #302

**Comment by james-munson** [comment]
removing a stand RL plugin and extending its functionally does not hurt

**Comment by zeruth** [comment]
Yeah i'd honestly prefer them to be seperated. it would make keeping wasd up to date easier. not like it'd be the end of the world though

**Comment by ThatGamerBlue** [comment]
removing standard rl plugins can cause merge conflicts, we should keep edits to standard files to a minimum

**Comment by zeruth** [comment]
well removing / renaming at least. adding to them isn't so bad

**Pull request closed without merging**
