### PR TITLE
vorkathhelper: add wooxwalk tile indicator, wooxwalk tick indicator, path through acid and config

### PR DESCRIPTION
**Pull request by Lohouse**
WooxWalk: adds an indicator for the tiles best for wooxwalking as well as a tick indicator that tells you which tile to click on each tick. See: https://imgur.com/a/NowGhnY
Path through acid: alternative to wooxwalking, simply indicates the most efficient path during the acid phase. See https://imgur.com/a/P1CNKJj
Config: Adds settings to enable/disable wooxwalk (tile and tick) indicator, path through acid indicator, regular acid spots indicator and path through acid minimum length

### CODE REVIEW

**Comment by Ganom** [comment]
Looks good, but will need some work before we merge, at the moment, config caching needs to be added. That will be the standard for all plugins in the future, i will get to a full review later on.

👍

**Comment by Lohouse** [comment]
Ok, sounds good. There is also a slight issue that was already there before I started expanding this plugin: When you die or teleport after or during a vorkath fight, `NpcDespawned` and `GameObjectDespawned` aren't called which causes the overlay to not be removed. This is not a huge problem because the overlays check if the WorldPoints can be translated to LocalPoints before drawing anything, but I still think it could be handled better. It can be done with a simple `GameTick` event but since I've only been tinkering with RuneLite plugins for a few days, I'm not sure if there are other events or better ways to handle this.

**Comment by Lohouse** [comment]
The issue described above is now fixed. I also implemented config caching. Both fixes were tested and are working properly.

**Comment by Ganom** [comment]
I pr'd a few changes, once those are merged I'll approve.

**Pull request merged**
