### PR TITLE
Bank Plugin: Add option to enlarge bank pin numbers

### PR DESCRIPTION
**Pull request by f0rmatme**
Added option to enlarge bank pin numbers

### CODE REVIEW

**Comment by ThatGamerBlue** [comment]
wait for result of upstream 9491

**Comment by f0rmatme** [comment]
they do not like modifying much with the bank, doubt that will ever make it.
PR is over 26 days old.

**Comment by xKylee** [comment]
Will need testing as I think this may cause issues with typeable bank pin

**Comment by SRLJustin** [comment]
tested out this PR, bank interface still the same size, checked bank config and Large bank pin numbers is enabled

image

image

**Comment by xKylee** [comment]
We will also need to test that and typeable bank pins that have a 0 still work.

**Comment by f0rmatme** [comment]
I tested it and it works fine for me, bank numbers are enlarged and i can type the bank pin

**Comment by SRLJustin** [comment]
@f0rmatme now working after clean build, didn't realize scripts didn't get updated from soruce

**Pull request merged**
