### PR TITLE
Adds an option to make the boosts plugin look kinda neat

### PR DESCRIPTION
**Pull request by tomcylke**
code is garbage I'll try to make it less garbage tomorrow sorry thanks

### CODE REVIEW

**Comment by tomcylke** [comment]
https://gyazo.com/86c697f0f5cddbcc3e9079c73c4943c5 looks like this

**Comment by james-munson** [comment]
i really like this, sick. thanks

**Comment by zeruth** [comment]
It is a very good submission, Look forward to more people like you coming along

**Comment by liq7z** [comment]
N I C E!

**Pull request merged**
