### PR TITLE
playerscouter: fix conmod exception, and various other updates.

### PR DESCRIPTION
**Pull request by Ganom**
Since config caching is now handled by config manager, I'm reverting the local caching being done as well. The performance difference is negligible, but looks much better.

### CODE REVIEW

**Comment by Owain94** [comment]
I'm not even sure if we actually merged that configManager change, i don't think so

**Comment by Ganom** [comment]
> 
> 
> I'm not even sure if we actually merged that configManager change, i don't think so

I could've swore we did, but you are correct, we did not.

**Comment by zeruth** [comment]
I skipped those commits.

**Comment by Ganom** [comment]
reverted the config changes

**Pull request merged**
