### PR TITLE
Update my barb assault plugin

### PR DESCRIPTION
**Pull request by rlw0014**
Sorry if there are tons of commits... wanting to squash them but not sure the best method.

### CODE REVIEW

**Comment by rlw0014** [comment]
Yikes I was right.. really need to squash :(

**Comment by Ganom** [comment]
Haha, yeah thats quite a few commits to squash

**Comment by gazivodag** [comment]
Don't worry about the commits. As long as the files modified are related to what you're PR'ing, I'll look at it in a sec

**Comment by ThatGamerBlue** [comment]
dont worry too much about squashing, we can squash on merge

**Comment by zeruth** [comment]
Really, I encourage you do as many commits as you need, it's as easy as us pushing a button to squash it all into one commit when we merge, and it makes that commit message much easier to make

**Comment by rlw0014** [comment]
Thanks everyone for the encouragement. I only wanted to contribute because I was shown that you guys somehow found my code for the ba plugin where it calculates total egg count and vial hp healed as collector and healer, respectively.

**Pull request merged**
