### PR TITLE
Clean plugin management pom maven

### PR DESCRIPTION
**Pull request by james-munson**
Remove second reference to maven-compiler-plugin version, as it is defined in the pluginManagement
Added maven-surefire-plugin version to pluginManagement as it is used in the parent and cache module
Add reproducible-build-maven-plugin version to pluginManagement as it is used in the parent and runelite-client module
Add spring-boot-maven-plugin version to pluginManagement as it is used in the http-service and cache-updater module

### CODE REVIEW

**Comment by Ganom** [comment]
This will also likely make it into base runelite.

**Comment by james-munson** [comment]
> This will also likely make it into base runelite.

its a really old pr

**Comment by Ganom** [comment]
> 
> 
> > This will also likely make it into base runelite.
> 
> its a really old pr

it was reviewed and approved 11 hours ago?

**Comment by james-munson** [comment]
> it was reviewed and approved 11 hours ago?
ya i was looking at the date it was made, still these been pull request for a while, doesn't hurt to pull them before runelite

**Comment by Ganom** [comment]
> 
> 
> > it was reviewed and approved 11 hours ago?
> 
> ya i was looking at the date it was made, still these been pull request for a while, doesn't hurt to pull them before runelite

it creates annoying conflicts to deal with when we merge.

**Comment by james-munson** [comment]
you can resolve that with just clicking one button with intellj

**Pull request closed without merging**
