### PR TITLE
Barbarianassault merge

### PR DESCRIPTION
**Pull request by se7enAte9**
Most of the stuff left to be done is minor. So it's very very much still a rough draft. If you see anything that should be done differently or could be done better please let me know.

- [x] [General] Fix prayer metronome - no sound
- [x] [Attacker] Add ranger/fighter tagging
- [x] [Healer] Fix healer codes - Add timers
- [x] [Healer] Add healer menu options
- [x] [Healer] Add shift overstock
- [x] [Healer] Add cntl healer to top of menu
- [x] [General] Add NPC death timers from another repo
- [x] [Collector/Healer] Redo some menus options / add deprioritization of eggs/healers instead of hiding
- [x] [Defender] Prioritize Walk Here over bait
- [x] [General] Fix checkstyle / remove useless comments/todos

### CODE REVIEW

**Comment by f0rmatme** [comment]
you could many use the new soundmanager to play sounds for like when to heal etc

**Comment by se7enAte9** [comment]
Just about done with this if anyone can test it out. I'll probably only be doing another small commit cleaning some stuff up and fixing one or two more things I've found. Some stuff I'll add later are the sound effects @f0rmatme suggested, and a couple other small overlay/menu changes such as only allowing the egg to be passed to a player or deprioritizing the exit ladder in game. If anyone else had any suggestions feel free to let me know.

**Comment by f0rmatme** [comment]
feel free to add custom sounds just for BA

**Comment by se7enAte9** [comment]
resolved conflicts

**Comment by Ganom** [comment]
👍

**Pull request merged**
