### PR TITLE
menuentryswapperplugin: Added Sarachnis crypt swap

### PR DESCRIPTION
**Pull request by Crystalknoct**
Added quick swap to sarachnis crypt.

### CODE REVIEW

**Comment by Kyleeld** [comment]
if the option is quick-enter, you would be better off adding this to the above option `else if (this.swapQuick && option.equals("enter")) by doing the below:

`		else if (this.swapQuick && (option.equals("enter") || option.equals("enter-crypt")))
		{
			swap(client, "quick-enter", option, target, true);
		}`

**Comment by Crystalknoct** [comment]
So that one line works for all quick enters?

**Comment by Kyleeld** [comment]
> So that one line works for all quick enters?

Any which have an option of enter or enter-crypt

**Comment by Kyleeld** [comment]
Awaiting changes detailed. @Crystalknoct I can make them if you don’t want to

**Comment by Crystalknoct** [comment]
I can attempt changes when I'm home just at work rn

**Comment by Kyleeld** [comment]
No worries, give me a shout if needed

**Pull request merged**
