### PR TITLE
Pvp loot value message

### LINKED ISSUE #495: Pk'd calculator in chatbox
a pk'd loot calculator? Basicly what Exilent has, so maybe winnetou is willing to help out? 

E.G:
https://gyazo.com/2306550530d31fbccd9f600588d29e4e @

### PR DESCRIPTION
**Pull request by pklite**
fixes #495 looks like 
image

### CODE REVIEW

**Comment by Kyleeld** [comment]
would be better off moving this to loot tracker i think to keep inline with other chat loot messages?

**Comment by pklite** [comment]
will do in a bit

**Comment by pklite** [comment]
> (WorldType.isPvpWorld(client.getWorldType())
> 
> this doesnt include high risk worlds, only DMM and PVP worlds :)

Is the high risk pvp world counted as PVP world, high risk world, or both? I can check in a few mins

**Comment by Kyleeld** [comment]
will need to add high risk world in then good to go :)

**Pull request merged**
