### PR TITLE
plugins: reduce config calls by saving and reusing values, misc performance tweaks.

### PR DESCRIPTION
**Pull request by sdburns1998**
Using singletons for events that are called frequently.
Parallelize plugin loading
Small misc changes to plugins (caching or guarding)
Fix sidebar from disappearing when expanding sidebar in full-screen mode and resizing the client afterwards.

### CODE REVIEW

**Comment by Kyleeld** [comment]
@sdburns1998 please re-base, some of these plugins/overlays are outdated by recent pulls :(

**Comment by sdburns1998** [comment]
Will do after I’ve done all plugins

**Comment by f0rmatme** [comment]
CookingPluginTest IdleNotifierPluginTest and more are are throwing errors

**Comment by sdburns1998** [comment]
@f0rmatme yeah I know it’s guicing circular dependencies in the tests because of the changes, still a WIP will fix test afterwards.

**Pull request merged**
