### PR TITLE
Zulrah WIP

### PR DESCRIPTION
**Pull request by Ganom**
Too tired to continue, team effort on this one boys.

Todo:
- [ ] Integrate tick counts into plugin.
- [ ] Integrate tick counts into overlay.
- [ ] Count down ticks during correct phase.

### CODE REVIEW

**Comment by kaffeknugen** [comment]
Why not just take the zulrah plugin fron runeliteplusplus? A really good plugin that cant be any better.

**Comment by ThatGamerBlue** [comment]
@kaffeknugen see #faq in our discord server

**Comment by Kyleeld** [comment]
Whilst it was a good plugin, there was a few features missing from it, on top of this it was hard to add code to due to the coding structure. This one is better imo

**Comment by ThatGamerBlue** [comment]
@Ganom can you edit the pull request comment to have a list of what still needs to be done in the plugin?

**Comment by Ganom** [comment]
> 
> 
> @Ganom can you edit the pull request comment to have a list of what still needs to be done in the plugin?

Done, I added all the tick counts for each rotation, it just needs to be added, but I lack the experience with enums to do that.

**Comment by supermxn** [comment]
bump any updates?

**Comment by Ganom** [comment]
Tooooooooooooooooo busy

**Pull request closed without merging**
