### PR TITLE
Plugin: xp drop change damage -> scraped npcstats and xpmodifier

### PR DESCRIPTION
**Pull request by sdburns1998**
Simplify xp drop damage 
NPCManager use scrape data from wiki and add xpmodifier based on those stats (credits: TheStonedTurtle)

Damage drops shouldn't be way off anymore on NPC's with a xpmodifier, it's certainly not perfect and it still can be a bit off ( -> vorkath for example) but in most cases it'll be correct now or at least way closer than before

The changes on the xp drop will also fix the damage above NPCs while training other stats than combat skills (for example doing a fruit tree run caused damage counter on top of farmers when paying them to remove a tree)

### CODE REVIEW

**Comment by sdburns1998** [comment]
Can someone test the damage drop against a player?

**Comment by Ganom** [comment]
Aww, so no more 2000 damage hits on farmers? :(

<3

**Comment by sdburns1998** [comment]
TODO: fix login tick?

**Comment by Lucwousin** [comment]
Just me or are you missing the xp drop script

**Comment by sdburns1998** [comment]
Still unstaged indeed, thanks for noticing @Lucwousin

**Pull request merged**
