### PR TITLE
Added plugin Gelogger

### PR DESCRIPTION
**Pull request by f0rmatme**

### CODE REVIEW

**Comment by Ganom** [comment]
Already exists with http api

**Comment by Ganom** [comment]
image

**Comment by f0rmatme** [comment]
I find the utility of having the local flatfile very useful, maybe it should just be added into the ge plugin?

**Comment by chrisjohnson** [comment]
Doesn't seem appropriate to bake an unnecessary feature into a plugin that many others would use. What about a local file makes it better to use than an API?

**Pull request closed without merging**
