### PR TITLE
Vorkath refactor + Fire ball ("tick fire") overlay

### PR DESCRIPTION
**Pull request by Infinitay**
- Uses ProjectileMoved and AnimationChanged
  - Changed overlay to display the current phase vorkath is on
   - No longer shows how many attacks till NEXT phase
   - Shows how many attacks till CURRENT phases special attack
 - Added fire bomb to overlay during acid phase (tick-attack)
 - Removed ZombifiedSpawn class as it is unnecessary
 - ~~Added fire bomb attack notification~~ Removed, its in #513 (needs to be reworked there is a "flaw")

(Click for Video Snippet)
[Vorkath Refactor](https://streamable.com/s/gy6qw/aufgwl)

### CODE REVIEW

**Comment by Ganom** [comment]
Very nice work 👍

**Comment by Infinitay** [comment]
> Since you modified this so much, It would be good to put your name and github link in the license 😃.
> 
> If you would rather not, let me know and i'll merge without it.

Sure, do you have any requests on how? ie do you want me to remove rl+ from the license or put my name before/after or you dont care

**Comment by Ganom** [comment]
> 
> Sure, do you have any requests on how? ie do you want me to remove rl+ from the license or put my name before/after or you dont care

Put your name after, or before, it doesn't matter.

**Comment by Lucwousin** [comment]
This all looks fine to me, with one exception. There's no reason to add the overlays to overlaymanager on startup and remove them on shutdown. It's checking every frame if the plugin has a vorkath right now, even if you're fishing on karamja (for example). If you instead add the overlays when the npc spawns and remove it when it despawns you're saving 50 checks every second. This is a problem most plugins have atm but it's worth it to change imo

**Pull request merged**
