### PR TITLE
Loot tracker update

### PR DESCRIPTION
**Pull request by pklite**
Adds PvP Player deaths to the runelite loot tracker, adds local NPC and Player loot record persistence via json, still have a few more things planned

- [x] Add loot record local persistence 
- [x] Add player deaths
- [x] Optionally separate loot by local player account username
- [x] Add ability to sort loot entries in the panel by amount, type, account, etc

### CODE REVIEW

**Comment by pklite** [comment]
This is finished except the sorting is a bit bugged, I'm on vacation for the next week so someone can either fix while i'm gone or i can get to it when i get back.

**Comment by f0rmatme** [comment]
> [ERROR] /home/travis/build/runelite-extended/runelite/http-service/src/main/java/net/runelite/http/service/loottracker/LootTrackerService.java:[145,65] no suitable constructor found for LootRecord(java.lang.String,net.runelite.http.api.loottracker.LootRecordType,java.util.List<net.runelite.http.api.loottracker.GameItem>,java.time.Instant)

**Comment by pklite** [comment]
> ```
> [ERROR] /home/travis/build/runelite-extended/runelite/http-service/src/main/java/net/runelite/http/service/loottracker/LootTrackerService.java:[145,65] no suitable constructor found for LootRecord(java.lang.String,net.runelite.http.api.loottracker.LootRecordType,java.util.List<net.runelite.http.api.loottracker.GameItem>,java.time.Instant)
>     constructor net.runelite.http.api.loottracker.LootRecord.LootRecord() is not applicable
>       (actual and formal argument lists differ in length)
>     constructor net.runelite.http.api.loottracker.LootRecord.LootRecord(java.lang.String,java.lang.String,net.runelite.http.api.loottracker.LootRecordType,java.util.Collection<net.runelite.http.api.loottracker.GameItem>,java.time.Instant) is not applicable
>       (actual and formal argument lists differ in length)
> ```

1 min ill fix

**Comment by pklite** [comment]
done. if you guys like this can be merged to gather feedback

**Pull request merged**
