### PR TITLE
Removes API from Slayer Plugin.

### PR DESCRIPTION
**Pull request by Hermetism**
The only caveat is that you can't use !Task or !Points anymore, but its a small price to pay for not being tracked by RuneLite.

### CODE REVIEW

**Comment by SRLJustin** [comment]
no thanks :\

**Comment by Hermetism** [comment]
Its like you don't understand what that API is doing at all tbh.

**Comment by Hermetism** [comment]
Toxic trash.

**Comment by Kyleeld** [comment]
I’d prefer if you didn’t flame people over an opinion. You would be better off porting this to our api, rather than crying because someone said no thanks

**Pull request closed without merging**
